# yaml-language-server: $schema=https://static.trunk.io/pub/trunk-yaml-schema.json
version: 0.1
required_trunk_version: ">=1.7.1-beta.9"

# Applicable linters and actions will run with these runtime versions
runtimes:
  enabled:
    - go@1.25.6
    - java@25
    - node@22.16.0
    - python@3.10.8

lint:
  # By sourcing this plugin, repos will enable these linters
  enabled:
    - biome@2.3.10
    - clippy@1.92.0
    - cspell@9.6.0
    - git-diff-check
    - gitleaks@8.30.0
    - markdownlint-cli2@0.20.0
    - pyright@1.1.408
    - ruff@0.14.13
    - rustfmt@1.92.0
    - dotenv-linter@4.0.0
    - shellcheck@0.11.0
    - shfmt@3.12.0
    - stylua@2.3.1
    - dart@3.10.7
    - prettier@3.8.0:
        packages:
          - prettier-plugin-java@latest
          - prettier-plugin-packagejson@latest
          - "@prettier/plugin-xml@latest"
          - prettier-plugin-prisma@latest
          - prettier-plugin-sh@latest
          - prettier-plugin-sql@latest
          - prettier-plugin-tailwindcss@latest

  disabled:
    - eslint
    - google-java-format
  # Sourcing repos will have these configs available to applicable linters
  exported_configs:
    - configs:
        - configs/biome.json
        - configs/clippy.toml
        - configs/cspell.json
        - configs/.markdownlint-cli2.jsonc
        - configs/pyrightconfig.json
        - configs/ruff.toml
        - configs/rustfmt.toml
        - configs/prettier.config.json
        - configs/.stylua.toml

  definitions:
    - name: prettier
      files:
        - markdown
        - java

# By sourcing this plugin, repos will enable these actions
actions:
  enabled:
    - trunk-announce
    - trunk-cache-prune
    - trunk-upgrade-available
    - trunk-check-pre-push
    - trunk-fmt-pre-commit

downloads:
  - name: trunk-analytics-cli
    downloads:
      - os:
          linux: unknown-linux
          macos: apple-darwin
        cpu:
          x86_64: x86_64
          arm_64: aarch64
        url: https://github.com/trunk-io/analytics-cli/releases/download/${version}/trunk-analytics-cli-${cpu}-${os}.tar.gz
tools:
  definitions:
    - name: trunk-analytics-cli
      download: trunk-analytics-cli
      known_good_version: 0.8.1
      shims: [trunk-analytics-cli]
      health_checks:
        - command: trunk-analytics-cli --version
          parse_regex: trunk flakytests ${semver}
  enabled:
    - gh@2.83.2
    - grpcui@1.4.3
    - gt@1.7.14
    - trunk-analytics-cli@0.12.2
